package gogcoll

// Reduce will iterate over the values in the iterator and chain the values together
// with the previous value generated by the function. The initial parameter will be
// the start of this chain, and the result of the last call will be the result of the
// Reduce function call. This function is sometimes known as Fold or Inject instead of
// Reduce.
func Reduce[T any, R any](values Iterator[T], initial R, f func(R, T) R) R {
	acc := initial

	values.Each(func(value T) {
		acc = f(acc, value)
	})

	return acc
}
